bump_version: null
lint:
  plugin_includes: False
  actions_awsfulltest: False
nf_core_version: 3.2.0
org_path: null
repository_type: pipeline
template:
  author: Esteban Peguero Sanchez
  description: A cool pipeline
  force: true
  is_nfcore: true
  name: transcriptassembler
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.0.0dev
update: null
