nf_core_version: 2.14.1
repository_type: pipeline
template:
  author: "Harshil Patel, Phil Ewels, Rickard Hammar\xE9n"
  description: RNA sequencing analysis pipeline for gene/isoform quantification and
    extensive quality control.
  force: false
  is_nfcore: true
  name: rnaseq
  org: nf-core
  outdir: .
  version: 3.17.0dev
