name: cmscan
description: Download files 
keywords:
  - sort
tools:
  - wget:
      description: Classification of RNAs.
      homepage: https://github.com/EddyRivasLab/infernal
      documentation: http://eddylab.org/infernal/
      tool_dev_url: https://github.com/EddyRivasLab/infernal
      doi: ""
      licence: ["BSD"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
  - fasta_file:
      type: string
      description: path to the input fasta.
  - clanin_file:
      type: string
      description: path to the clan information file.
  - cm_file:
      type: string
      description: path to the covariance model, also the files with extensions cm_file.[ilf,ili, ilp] are required. 
         These are the outputs of cmpress.

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

  - mrum-geome.cmscan:
      type: file
      description: Detailed output
      pattern: "*"

  - mrum-genome.tblout:
      type: file
      description: Short output version
      pattern: "*"

authors:
  - "@EPegueroS"
