contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #giotto channel"
    url: https://nfcore.slack.com/channels/giotto
    about: Discussion about the nf-core/giotto pipeline
